### PR TITLE
Dev Update

### PR DESCRIPTION
**Pull request by wildone**
add dev dotfile profile
add java dotfile profile
add more general tools

### CODE REVIEW

**Comment by audiolion** [comment]
I wonder if this crosses the line of opinionated choices in a few spots, for example installing guis, a 'matrix' terminal theme, apps like spotify, etc. Some of these are personal choices and not really universal things that are useful to people trying to get a dev setup on their macs. Though I guess you can always opt-out of them so maybe it isn't a big deal

**Comment by donnemartin** [comment]
Hi @wildone, thanks for time to submit a PR!

I think a previously posted comment on this PR is valid (seems to have been removed by the author):

>Some of these are personal choices and not really universal things that are useful to people trying to get a dev setup on their macs

Also, there are currently 63 commits in this single PR.  I think one logical change per PR is ideal.  I didn't have a chance to look at all 63 commits, perhaps you can submit PRs for each of these?

1f7effe2bc5419aab8945a1fcf7f43ca8e0cb951
1b668b17704bab00bf581519e98192d2ce33a56e

For 1b668b17704bab00bf581519e98192d2ce33a56e which fixes #32, it looks like you added java7.  I don't do much Java development, is this necessary?

-Donne

**Comment by audiolion** [comment]
Hey, I removed the previous comment because I felt that the personal choices could be opt-out given the nature of how dev-setup works. Potentially we could have these things set up as default opt-out but the person installing can specify flags or run these extra scripts to opt-in to the more opinionated choices. So I felt it could honestly go either way and I wanted to leave the decision up to you @donnemartin.

I do agree that splitting up this massive PR into smaller PR's that are more narrowly focused and easier to test/rollback/track history on is much better

**Comment by wildone** [comment]
Hey guys that for this good work its a great project very comprehensive and helpful

@donnemartin 
brew install aircrack-ng #needs java 1.7+

sorry guys did not have much time to play with this, personally I would prefer all of this to be though ansible, but that would have to be a project for the future.

I think all of this is setup is personal and opinionated, hence its good to have a base which you can just modify of purpose. I don't particular use majority of existing tools you had there but its ok its not windows so does not hurt. I just went to add more dev roles to support Devs who probably using linux if they are serious.

**Comment by donnemartin** [comment]
@audiolion @wildone thanks for the feedback!

**Pull request closed without merging**
